#!/bin/bash
source $PHPBREW_HOME/env

export PATH=$PATH:$PHPBREW_HOME/bin \
 && phpbrew use $MAGENTO_PHP_BREWED_VERSION \
 && phpbrew ext install xdebug \
 && phpbrew ext install gd \
                        --with-jpeg-dir=/usr \
                        --enable-gd-native-ttf
