#!/bin/bash
source ~/.phpbrew/bashrc

export PATH=$PATH:$PHPBREW_HOME/bin \
    && phpbrew use $MAGENTO_PHP_BREWED_VERSION \
    && umask 0002 
    && exec /opt/phpbrew/php/php-$MAGENTO_PHP_BREWED_VERSION/sbin/php-fpm
